#!/usr/bin/python
import tkinter
from tkinter import *

from tqdm import tk

frame = Tk()
frame.geometry("750x300")
frame.title("Register")

my_file_location = "C:\\Users\\loyd_\\IdeaProjects\\UISample\\dataFile"


studentInfoLabel = tkinter.Label(frame, fg='blue', bg='grey', text="Student Information",
                                 font=("arial", 16, "bold")).place(x=275, y=5)
nameLabel = tkinter.Label(frame, fg='Black', text="Name:", font=("arial", 12)).place(x=50, y=60)
lastNameLabel = tkinter.Label(frame, fg='Black', text="Last Name", font=("arial", 12)).place(x=150, y=90)
firstNameLabel = tkinter.Label(frame, fg='Black', text="First Name", font=("arial", 12)).place(x=300, y=90)
middleNameLabel = tkinter.Label(frame, fg='Black', text="Middle Name", font=("arial", 12)).place(x=450, y=90)

ageLabel = tkinter.Label(frame, fg='Black', text="Age:", font=("arial", 12)).place(x=50, y=140)
bdayLabel = tkinter.Label(frame, fg='Black', text="Birth Date:", font=("arial", 12)).place(x=200, y=140)
genderLabel = tkinter.Label(frame, fg='Black', text="Gender:", font=("arial", 12)).place(x=400, y=140)

lastName = StringVar()
middleName = StringVar()
firstName = StringVar()

lastNameField = Entry(frame, textvar=lastName).place(x=130, y=65)
fistNameField = Entry(frame, textvariable=firstName).place(x=280, y=65)
middleNameField = Entry(frame, textvar=middleName).place(x=432, y=65)

age = StringVar()
bDate = StringVar()
gender = StringVar()

ageField = Entry(frame, textvar=age, width=3).place(x=100, y=140)
bdateField = Entry(frame, textvar=bDate, width=15).place(x=300, y=140)
genderField = Entry(frame, textvar=gender, width=5).place(x=470, y=140)


def file_writer():
    last = "Last Name: " + lastName.get() + ", " + "First Name: " + firstName.get() + "\tMiddle Name: " + middleName.get() + "\nAge: " + age.get() + "\tBirth Date: " + bDate.get() + "\tGender: " + gender.get()
    with open(my_file_location, 'w') as my_file:
        my_file.write(last)


registerButton = Button(frame, text="Register", width=10, fg='black', command=file_writer).place(
    x=300, y=200)

frame.mainloop()
